### ISSUE TITLE
Large videohub 288

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion-module-bmd-videohub#16]
Hi.
I'm trying to control the largest 288x288 videohub, but it makes Companion very slow to respond to anything.  I've not wiresharked the data yet, but I think it's pulling lots of data from the videohub.  As soon as i disable the interface it returns to normal CPU levels.
Thanks

**Comment by willosof** [comment]
Hmm, 288x288 shouldn't really be a problem for companion, but i've never tested it. Could you do a wireshark and upload it here? :)

**Comment by Julusian** [comment]
I expect this is a case of the module flooding companion with data.
For a 40x40 videohub, it is generating 3282 presets, totalling 1.3MB of json. I expect this to scale roughly linearly based on the number of inputs, so for a 288 input model, thats somewhere in the region of 165888 presets, totalling 65MB.

The module doesn't look conservative at emitting updates to those (it uses the input names when generating them, so whenever one changes they will need invalidating), which could cause a bit of a flood of data if they change often

**Comment by Julusian** [comment]
I think this is resolved now. see #31
