### ISSUE TITLE
Documentation improvement?

### ISSUE THREAD

**Issue by plocher** [bitfocus/companion-module-bmd-videohub#19]
As a newb for all of this, I'm finding this module hard to understand/use, probably because the help.md file is oriented towards "what it does" rather than "how to do it" -for me,  translating the underlying concepts into Companion button behavior isn't very intuitive.  Thanks to your well appreciated efforts, I'm making things sort-of work, but I can't but feel that there is a better way that I've completely missed!

To make the learning curve a bit easier, could you add some worked examples of how to do common tasks, such as

Connect destination X to source Y 

- This can be done with one button/action, as in
  - Action: Route (Select destination) (Select Source)

- or spread between multiple buttons (press a dest button, then press a src one...)

  - button 1: Action: Select destination (choose destination)
  - button 2: Action: Route source to selected destination (choose source)

... etc ...

Connect destination named "Xname" to source named "Yname"
Connect destination X to the same source as found on destination X2
Set source Y name to "Yname"
Set destination X name to "Xname"

Bonus points if you can add in feedback actions/explanations for the above...

**Comment by josephdadams** [comment]
@plocher if you wanted to consider making a more helpful/verbose HELP.md file, we would accept the pull request on it.
