### ISSUE TITLE
2ME Constellation HD continually disconnects

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-bmd-videohub#24]
ATEM 2ME Constellation HD continually connects and disconnects from the videohub module. 

The videohub module does automatically recognize the correct number of inputs, and when it is connected the labels and functions do work. 

Running Companion 2.3.1 and also tested beta 2.4.0-4771 on a M1 Mac.

Also, I've noticed in the module settings, the number of Input Count and Output Count are not remembered after saving. Shortly after reconnecting it defaults back to the initial number (on the 2ME Constellation HD its 45 In and 16 Out).

![Screenshot 2022-11-11 at 3 17 25 PM](https://user-images.githubusercontent.com/76959770/201425573-bf4417bc-7d61-464a-8d2c-0a83e8470244.png)

**Comment by allen-harris** [comment]
This might be a dumb question, but why are you trying to use the videohub module to connect to an ATEM rather than the ATEM module?

**Comment by davidjoshuaford** [comment]
This was a legacy issue before variable routing existed in the atem module, but is now redundant with v3 approaching. I'll close it out.
