### ISSUE TITLE
Feature Request: Add Short Name variables to videohub module

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-bmd-videohub#25]
Adding short name variables to the videohub module would help create buttons that are much easier and consistent to read. 

Currently the labels pull the long name - ie:

`$(videohub:output_1)\n$(videohub:output_1_input)`

![Screenshot 2022-11-11 at 3 31 17 PM](https://user-images.githubusercontent.com/76959770/201426771-d9c4ebcc-a93e-4207-a650-df9c82d59f00.png)

So at the moment I'm using the ATEM module's short name codes, since the 4-character limit on the Short Names makes the buttons easier to read: 

`$(atem:short_8001)\n$(atem:aux1_input)`

![Screenshot 2022-11-11 at 3 32 32 PM](https://user-images.githubusercontent.com/76959770/201426893-576ba85a-8d91-4363-9dd4-08be18dd12db.png)

To streamline, it would be helpful if the videohub module could read short names, rather than having to also add in the atem module. 

Thank you!

**Comment by Julusian** [comment]
This isn't possible to do in this module. The videohub protocol has no concept of short and long names, that is a purely atem thing.

**Comment by davidjoshuaford** [comment]
Thanks for looking into in Julian!
