### ISSUE TITLE
[BUG]videohub 288 crashes module in Companion 3.0.0 rc1

### ISSUE THREAD

**Issue by allen-harris** [bitfocus/companion-module-bmd-videohub#31]
I just updated to Companion 3.0.0 rc1 on Windows 10.  When it tries to connect to my 288 square videohub it crashes the module.  It works fine with my 12x12 cleanswitch.  In previous versions of Companion, I noticed that it took a minute or so to stabilize after the initial connection as it gathered the input and output names and status of the router.  Once it loaded, it was responsive.

With the size of the matrix, could the timeout on getting the date be too short?

I have rolled back to Companion 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863), and it is working fine again.

Thanks for your help and for writing this module.

EDIT: I just installed Companion 3.0.0 rc1 on Ubuntu 22.04 and it also has the same issue.

From the Linux instance:

```
Starting up module class: c
Sentry disabled
Module-host accepted registration
error: Failed to init: Error: Call timed out Error: Call timed out
    at t.IpcWrapper.sendWithCb (/opt/companion/main.js:2:2368080)
    at Object.init (/opt/companion/main.js:2:8093140)
    at l.<anonymous> (/opt/companion/main.js:2:8102009)
    at l.emit (node:events:513:28)
    at l.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/opt/companion/main.js:2:2355696)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
system: ** Connection stopped **
system: ** Connection started **
```

**Comment by Julusian** [comment]
This is a problem with the presets. Because its creating 288*288 presets to cover all of the routing, which is resulting in a blob of json over 70mb in size!

I've stopped it from generating some of those presets, limiting them to the first 20 input and outputs (number chosen arbitrarily), which keeps the size of the presets json below 1mb.

This will be in a beta build soon, let me know if it isnt working for you. I haven't been able to test against a videohub, only setting the size in the config

**Comment by allen-harris** [comment]
Thanks Julusian.  Once the beta is up I can test it against my videohub.

**Comment by Julusian** [comment]
It is in `3.0.0+5933` and newer betas

**Comment by PeterLawrence1** [comment]
Have tested v2.02 of the module with 3.0.0 RC 1 on Apple Silicone Macbook Air and do not get this issue, I do on Raspberry Pi 4
Videohub 72x144

**Comment by bryce-seifert** [comment]
Tested with beta `3.0.0+5933` and it seems resolved for me

**Comment by allen-harris** [comment]
I have now tested 3.0.0+5934-beta-bd3fdf25 on Ubuntu, and it is not crashing anymore.

Allen
