### ISSUE TITLE
The videohub interface doesn't send the PING command

### ISSUE THREAD

**Issue by simias** [bitfocus/companion-module-bmd-videohub#35]
Hello and thank you for the great project!

I work on a video device that implements the videohub protocol that is normally used with Blackmagic's own panels. Some clients also use Stream Decks through Companion to achieve the same thing.

This works mostly well with one small issue: my software disconnects Companion every 30s in case of inactivity (i.e. no message received on the TCP connection).

This isn't a problem usually because the Blackmagic hardware panels send a PING ever 2s while the Blackmagic Master Control Pro software does it every 5s, so this is more than enough to avoid timing out any active connection.

However as far as I can tell this companion module never sends PINGs, leading to timeouts in case of inactivity.

Naturally the official specification of the protocol is fairly loose and doesn't mandate the use of PING commands, so  technically this module isn't doing anything wrong, but I thought I'd raise the issue because I think it may still be worthwhile to think about sending regular pings both in order to better emulate the behaviour of first-party hardware and software and also in order to avoid having dangling TCP connexions in case of inactivity. This might help with issue #8 for instance.

**Comment by Julusian** [comment]
A PR to resolve this would be appreciated.
I agree it would probably resolve #8 and an issue mentioned in a comment in the bmd-atem module which says that connecting this module to an atem results in frequent disconnects https://github.com/bitfocus/companion-module-bmd-atem/issues/157#issuecomment-1331608488.

**Comment by Julusian** [comment]
I have fixed this, it will be in the betas shortly
